server:
  port: 8090  # 원하는 포트 번호로 설정
spring:
  application:
    name: underwriting-service
  datasource:
    url: ENC(AW0BEC1fe4yqlD0Yg5Iix3VGIw7VAyBqwquScxkDODgz0oV+T9GgAASj+scyUnbq2TSP++xD/YtBaOaKaUXvDQ==)
    username: ENC(sPeethAj11kGlF1rT5LAfMB3bjbXQKWR)
    password: ENC(5aDgbxKKn0AL7Z5go6skL5dAya4MbRl4)
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 4000
      validation-timeout: 3000
      idle-timeout: 160000
      max-lifetime: 175000
      minimum-idle: 5
      maximum-pool-size: 1000
      pool-name: BaseHikariPool
  #----------------------------------------------------------------------------------------------
  # jpa configuration
  #----------------------------------------------------------------------------------------------
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc.time_zone: Asia/Seoul
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: com.mooo.devforin.appservice.config.querydsl.NamingStrategyConfig

token:
  expire:
    # 5분
    time: 1209600000 # (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
#    time: 300000
#    time : 5000
  secret : thisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkey
#

api:
#Swagger
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /**
    - /api/v1/auth/login

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

openAI:
  API:
    KEY: ENC(pZVBaYbdxxrax7wta46BsvVlpSmoCcIpk+tTul44ZIE1en25d7rjYVeaDkVTMVHntNovL0TarsKrmW/0qsKtjNYaWOuXxusyh+R58Akzh39CJWS7+8+MZngbdWX354jvJoeNl9nT7AD2xtD3Jbhwvf7dLKb7+lkZQRpPylrjGYyJDra+m4HdlI1DLlvBKfDil8Pd9EfeSHgEhUfK4Xq8YMqmgwPZTEjwWuPQBcw2OhQ=)